### ISSUE TITLE
No module named 'experiment'

### ISSUE THREAD

**Issue by alcampbell25** [compmem/smile#146]
When I try to run the following:

(base) PS C:\Python_Scripts> python hello.py -s Subject99

I get the error:

Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    from smile.common import *
  File "C:\Users\campball\AppData\Local\Continuum\anaconda3\lib\site-packages\smile\common.py", line 11, in <module>
    from experiment import Experiment
ModuleNotFoundError: No module named 'experiment'

**Comment by alcampbell25** [comment]
(base) PS C:\Python_Scripts> python hello.py -s Subject99

I get the following error:
Traceback (most recent call last):
  File "hello.py", line 1, in <module>
    from smile.common import *
  File "C:\Users\campball\AppData\Local\Continuum\anaconda3\lib\site-packages\smile\common.py", line 11, in <module>
    from experiment import Experiment
ModuleNotFoundError: No module named 'experiment'

**Comment by beegica** [comment]
Hello! 

Sorry to see you are running into an error. It looks like you might be trying to run SMILE from a Python 3 environment, and SMILE is not compatible with Python 3 just yet. We are working on it though! Please let me know if running SMILE from a Python 2 environment fixes the issue!

B

**Comment by alcampbell25** [comment]
Thank you for the quick reply!
